<a href="https://colab.research.google.com/github/codemeharder21/MachineLearning/blob/main/PyTorch/Autograd.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
from torchvision.models import resnet18, ResNet18_Weights
model = resnet18(weights=ResNet18_Weights.DEFAULT)
data = torch.rand(1, 3, 64, 64)
labels = torch.rand(1, 1000)

Downloading: "https://download.pytorch.org/models/resnet18-f37072fd.pth" to /root/.cache/torch/hub/checkpoints/resnet18-f37072fd.pth
100%|██████████| 44.7M/44.7M [00:00<00:00, 98.4MB/s]


In [ ]:
data[:2],labels[:2]

In [ ]:
data.shape

torch.Size([1, 3, 64, 64])

In [ ]:
prediction = model(data) # forward pass

In [ ]:
loss = (prediction - labels).sum()
loss.backward() # backward pass

In [ ]:
optim = torch.optim.SGD(model.parameters(), lr=1e-2, momentum=0.9)

In [ ]:
optim.step() #gradient descent

In [ ]:
loss

tensor(-494.5357, grad_fn=<SumBackward0>)

In [ ]:

a = torch.tensor([2., 3.], requires_grad=True)
b = torch.tensor([6., 4.], requires_grad=True)

In [ ]:
Q = 3*a**3 - b**2

In [ ]:
external_grad = torch.tensor([3., 3.])
Q.backward(gradient=external_grad)

In [ ]:
a.grad

tensor([108., 243.])

In [ ]:
3*a**3-b**2

tensor([-12.,  65.], grad_fn=<SubBackward0>)

In [ ]:
b.grad

tensor([-12.,  -8.])

In [ ]:
c=torch.tensor([4., 3.], requires_grad=True)

In [ ]:
c.grad

In [ ]:
x = torch.rand(5, 5)
y = torch.rand(5, 5)
z = torch.rand((5, 5), requires_grad=True)

a = x + y
print(f"Does `a` require gradients? : {a.requires_grad}")
b = x + z
print(f"Does `b` require gradients?: {b.requires_grad}")

Does `a` require gradients? : False
Does `b` require gradients?: True


In [ ]:
from torch import nn, optim

model = resnet18(weights=ResNet18_Weights.DEFAULT)

# Freeze all the parameters in the network
for param in model.parameters():
    param.requires_grad = False

In [ ]:
model.fc = nn.Linear(512, 10)

In [ ]:
# Optimize only the classifier
optimizer = optim.SGD(model.parameters(), lr=1e-2, momentum=0.9)

In [ ]:
print("update 1")

In [ ]:
1

1